import TCustomErrors from "shared-types/Errors";

export enum MICROSERVICE_NAME_UPPERCASE_PLACEHOLDEREvents {
  MICROSERVICE_NAME_UPPERCASE_PLACEHOLDERError = "MICROSERVICE_NAME_UPPERCASE_PLACEHOLDERError",
}

export type MICROSERVICE_NAME_UPPERCASE_PLACEHOLDEREventsPayload = {
  [MICROSERVICE_NAME_UPPERCASE_PLACEHOLDEREvents.MICROSERVICE_NAME_UPPERCASE_PLACEHOLDERError]: TCustomErrors;
};
