import TCustomErrors from "shared-types/Errors";

export enum MICROSERVICE_NAME_UPPERCACE_PLACEHOLDEREvents {
  MICROSERVICE_NAME_UPPERCACE_PLACEHOLDERError = "MICROSERVICE_NAME_UPPERCACE_PLACEHOLDERError",
}

export type MICROSERVICE_NAME_UPPERCACE_PLACEHOLDEREventsPayload = {
  [MICROSERVICE_NAME_UPPERCACE_PLACEHOLDEREvents.MICROSERVICE_NAME_UPPERCACE_PLACEHOLDERError]: TCustomErrors;
};
