openapi: 3.0.0
info:
  title: Boilerplate
  version: 1.0.0
servers:
  - url: http://{{baseurl}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: Auth
    description: Authentication service for the whole boilerplate
paths:
  /auth/n/classic:
    post:
      tags:
        - Auth
      summary: Sign up classic
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: email@example.com
                password: password
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/n/sign-in/classic:
    post:
      tags:
        - Auth
      summary: Sign in classic
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: email@example.com
                password: password
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/z/refresh-token:
    get:
      tags:
        - Auth
      summary: Refresh Token
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/n/logout:
    get:
      tags:
        - Auth
      summary: Logout auth client from session by refresh token
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
