export enum ACCESS_RESSOURCES {
  "ROLE" = "ROLE",
  "*" = "*",
  "PUBLIC" = "PUBLIC",
  "AUTHENTICATED_CLIENTS" = "AUTHENTICATED_CLIENTS",
  "BAN_CLIENTS" = "BAN_CLIENTS",
  "SUSPEND_CLIENTS" = "SUSPEND_CLIENTS",
  "LIFT_BAN_AND_SUSPENSION" = "LIFT_BAN_AND_SUSPENSION",
  "MICROSERVICE_STATUS" = "MICROSERVICE_STATUS",
  "FILES" = "FILES",
  "BLOGS" = "BLOGS",
  "CATEGORY" = "CATEGORY",
}
